title: YuHasker
author: Betty & Geoffrey YuHasker
email: yuhasker@gmail.com
description: Homepage of the YuHasker Family Office

theme: minima
linkedin_username: betty-yuhasker
twitter_username: ghasker
github_username: hasker

header_pages:
  - team.md
  - portfolio.md
