title: YuHasker
author:
  name: Betty & Geoffrey YuHasker
  email: yuhasker@gmail.com
description: >
  Homepage of the YuHasker Family office
theme: minima
minima:
  social_links:
    linkedin: betty-yu-yuhasker-1607282
    twitter: ghasker
    github: hasker

